;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Theme Tweaks]
Pos=0,24
Size=1274,642
Collapsed=0
DockId=0xAFC85805,0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][StatusBar]
Pos=0,665
Size=1274,33
Collapsed=0

[Window][Dear ImGui Demo]
Pos=612,44
Size=588,680
Collapsed=0

[Window][Dear ImGui Demo/ResizableChild_478B81A3]
IsChild=1
Size=528,208

[Window][Dear ImGui Demo/Red_BEEF922B]
IsChild=1
Size=200,100

[Table][0x369EB90F,3]
Column 0  Weight=1.0000
Column 1  Weight=1.0000
Column 2  Weight=1.0000

[Table][0x2ACCE68A,3]
RefScale=20
Column 0  Width=125
Column 1  Width=125
Column 2  Width=125

[Table][0x951FCC8A,6]
RefScale=20
Column 0  Width=44 Sort=0v
Column 1  Width=65
Column 2  Width=103
Column 3  Width=105
Column 4  Weight=1.0000
Column 5  Width=-1

[Table][0x127BEAD2,7]
RefScale=20
Column 0  Width=76
Column 1  Width=173
Column 2  Width=173
Column 3  Width=173
Column 4  Width=173
Column 5  Width=173
Column 6  Width=173

[Docking][Data]
DockSpace ID=0xAFC85805 Window=0x079D3A04 Pos=0,24 Size=1274,642 CentralNode=1 Selected=0x83833CF9


;;;<<<Layout_655921752_Default>>>;;;

;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=true
ShowFps=true
[Theme]
Name=SoDark_AccentRed

;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{"MainDockSpace":2949142533}}
